export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";

export const POST_REGISTRATION = "POST_REGISTRATION";
export const POST_REGISTRATION_ERROR = "POST_REGISTRATION_ERROR";
export const POST_REGISTRATION_LOADING = "POST_REGISTRATION_LOADING";

export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_ERROR = "GET_EVENTS_ERROR";
export const GET_EVENTS_LOADING = "GET_EVENTS_LOADING";

export const GET_MY_EVENTS = "GET_MY_EVENTS";
export const GET_MY_EVENTS_ERROR = "GET_MY_EVENTS_ERROR";
export const GET_MY_EVENTS_LOADING = "GET_MY_EVENTS_LOADING";

export const POST_GO_EVENT = "POST_GO_EVENT";
export const POST_GO_EVENT_ERROR = "POST_GO_EVENT_ERROR";
export const POST_GO_EVENT_LOADING = "POST_GO_EVENT_LOADING";

export const POST_CANCEL_BOOKING_EVENT = "POST_CANCEL_BOOKING_EVENT";
export const POST_CANCEL_BOOKING_EVENT_ERROR =
  "POST_CANCEL_BOOKING_EVENT_ERROR";
export const POST_CANCEL_BOOKING_EVENT_LOADING =
  "POST_CANCEL_BOOKING_EVENT_LOADING";

export const GET_SHOP = "GET_SHOP";
export const GET_SHOP_ERROR = "GET_SHOP_ERROR";
export const GET_SHOP_LOADING = "GET_SHOP_LOADING";

export const POST_CREATE_EVENT = "POST_CREATE_EVENT";
export const POST_CREATE_EVENT_ERROR = "POST_CREATE_EVENT_ERROR";
export const POST_CREATE_EVENT_LOADING = "POST_CREATE_EVENT_LOADING";

export const POST_CREATE_SHOP_ITEM = "POST_CREATE_SHOP_ITEM";
export const POST_CREATE_SHOP_ITEM_ERROR = "POST_CREATE_SHOP_ITEM_ERROR";
export const POST_CREATE_SHOP_ITEM_LOADING = "POST_CREATE_SHOP_ITEM_LOADING";

export const GET_RATING = "GET_RATING";

export const POST_CHECK_ITEM = "POST_CHECK_ITEM";
export const  GET_CHECK_ITEM = "GET_CHECK_ITEM";


export const POST_CHANGE_EVENT = "POST_CHANGE_EVENT";

export const POST_DELETE_EVENT = "POST_DELETE_EVENT";